[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
  ignore = "git diff --quiet HEAD^ HEAD sub_dir/"
[build.environment]
  NODE_VERSION = "18.0.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
package = "@netlify/plugin-gatsby"
